name = "spi_two_devices"
description = "Demo program for 2 Raspberry Picoss talking to each other using SPI"
version = "0.0.1"

authors = ["Holger Rodriguez"]
maintainers = ["Holger Rodriguez <github@roseng.ch>"]
maintainers-logins = ["hgrodriguez"]

executables = ["spi_two_devices"]
[[depends-on]]  # Added by alr
pico_bsp = "1.1.0"  # Added by alr
[[depends-on]]  # Added by alr
gnat_arm_elf = "^11.2.3"  # Added by alr
